name: CMake
on:
  push:
    branches:
      - main
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # cannot specify filter for pull_request in on: above, so do it here
    runs-on: ubuntu-latest

    steps:
    - name: Clean workspace
      run: |
        echo "Cleaning up previous run"
        rm -rf "${{ github.workspace }}"
        mkdir -p "${{ github.workspace }}"

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init

    - name: Install Dependencies
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: sudo apt-get update && sudo apt-get install -yq git git-lfs sudo cmake gcc-arm-none-eabi  libnewlib-arm-none-eabi build-essential libstdc++-arm-none-eabi-newlib python3 python3-pip 
    - name: Compile
      run: git clone https://github.com/raspberrypi/pico-sdk.git && cd pico-sdk && git submodule update --init && cd .. && export PICO_SDK_PATH=pico-sdk/ && cd src && cmake ../pico-sdk && make -j4
      #credit to https://github.com/raspberrypi/pico-sdk/blob/master/.github/workflows/cmake.yml
